name: CI Tests

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master, develop]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Set up virtual display
              run: |
                  sudo apt-get update
                  sudo apt-get install -y xvfb
                # виртуальный дисплей
            - name: Run tests with virtual display
              run: |
                  xvfb-run pytest -v --alluredir=allure-results

            - name: Upload Allure results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: allure-results
                  path: allure-results